apiVersion: v1
kind: Service
metadata:
  labels:
    app: greet-message-service
  name: greet-message-service
  namespace: default
  
spec:
  
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: greet-message-service
  sessionAffinity: None
  type: NodePort

