spring:
  application:
    name: emp-service
  datasource:
      driverClassName: ${DB_DRIVER:org.h2.Driver}
      url: ${DB_URL:jdbc:h2:mem:testdb}
      username: ${DB_USER:sa}
      password: ${DB_PASSWORD:sa}
  jpa:
   hibernate:
      ddl-auto: none
   show-sql: true
  h2:
    console:
      enabled: true
      
server:
 port: 8081
 
eureka:
 client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
 
#debug: true